### ISSUE TITLE
关于 Google Analytics property

### ISSUE THREAD

**Issue by smd1121** [Phil-Fan/Phil-Fan.github.io#1]
Hi @Phil-Fan ~

我在我的 Google Analytics 看到了您仓库的统计信息，随后发现您在 [这一行](https://github.com/Phil-Fan/Phil-Fan.github.io/blob/master/mkdocs.yml#L91) 使用了我的 property。您可以查阅 [教程](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=google#setting-up-site-analytics) 来 setup 自己的 property 从而完成统计！您也可以注释掉以下 4 行来暂时解决这个问题：

```diff
 extra:
   analytics:
     provider: google
+    property: G-JT9BRCXKJJ
```

另外根据我的笔记本使用的协议：根据 [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.zh)，您可能需要在合适的地方给出署名；根据 [SATA](https://github.com/zTrix/sata-license)，您可能需要给我一个 star。感谢！🥰

**Comment by Phil-Fan** [comment]
感谢指出🥲👀





Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
From: 咸鱼暄 ***@***.***&gt;
发送时间: 11/08/2023, 09:58
To: Phil-Fan/Phil-Fan.github.io ***@***.***&gt;
抄送: PhilFan ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [Phil-Fan/Phil-Fan.github.io] 关于 Google Analytics property (Issue #1)





 
Hi @Phil-Fan ~
 
我在我的 Google Analytics 看到了您仓库的统计信息，随后发现您在 这一行 使用了我的 property。您可以查阅 教程 来 setup 自己的 property 从而完成统计！您也可以注释掉以下 4 行来暂时解决这个问题：
  extra:    analytics:      provider: google +    property: G-JT9BRCXKJJ
 
另外根据 CC BY-SA 4.0，您可能需要在合适的地方给出署名，感谢！🥰
